/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreativesRouteImport } from './routes/creatives'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AudiencesRouteImport } from './routes/audiences'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as AccountsIndexRouteImport } from './routes/accounts.index'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'
import { Route as AccountsIdRouteImport } from './routes/accounts.$id'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativesRoute = CreativesRouteImport.update({
  id: '/creatives',
  path: '/creatives',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiencesRoute = AudiencesRouteImport.update({
  id: '/audiences',
  path: '/audiences',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIdRoute = AccountsIdRouteImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/alerts': typeof AlertsRoute
  '/audiences': typeof AudiencesRoute
  '/campaigns': typeof CampaignsRoute
  '/creatives': typeof CreativesRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sync': typeof SyncRoute
  '/users': typeof UsersRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/clients/$id': typeof ClientsIdRoute
  '/accounts/': typeof AccountsIndexRoute
  '/clients/': typeof ClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/alerts': typeof AlertsRoute
  '/audiences': typeof AudiencesRoute
  '/campaigns': typeof CampaignsRoute
  '/creatives': typeof CreativesRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sync': typeof SyncRoute
  '/users': typeof UsersRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/clients/$id': typeof ClientsIdRoute
  '/accounts': typeof AccountsIndexRoute
  '/clients': typeof ClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/alerts': typeof AlertsRoute
  '/audiences': typeof AudiencesRoute
  '/campaigns': typeof CampaignsRoute
  '/creatives': typeof CreativesRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sync': typeof SyncRoute
  '/users': typeof UsersRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/clients/$id': typeof ClientsIdRoute
  '/accounts/': typeof AccountsIndexRoute
  '/clients/': typeof ClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/alerts'
    | '/audiences'
    | '/campaigns'
    | '/creatives'
    | '/login'
    | '/overview'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/sync'
    | '/users'
    | '/accounts/$id'
    | '/clients/$id'
    | '/accounts/'
    | '/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/alerts'
    | '/audiences'
    | '/campaigns'
    | '/creatives'
    | '/login'
    | '/overview'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/sync'
    | '/users'
    | '/accounts/$id'
    | '/clients/$id'
    | '/accounts'
    | '/clients'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/alerts'
    | '/audiences'
    | '/campaigns'
    | '/creatives'
    | '/login'
    | '/overview'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/sync'
    | '/users'
    | '/accounts/$id'
    | '/clients/$id'
    | '/accounts/'
    | '/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AlertsRoute: typeof AlertsRoute
  AudiencesRoute: typeof AudiencesRoute
  CampaignsRoute: typeof CampaignsRoute
  CreativesRoute: typeof CreativesRoute
  LoginRoute: typeof LoginRoute
  OverviewRoute: typeof OverviewRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SyncRoute: typeof SyncRoute
  UsersRoute: typeof UsersRoute
  AccountsIdRoute: typeof AccountsIdRoute
  ClientsIdRoute: typeof ClientsIdRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creatives': {
      id: '/creatives'
      path: '/creatives'
      fullPath: '/creatives'
      preLoaderRoute: typeof CreativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiences': {
      id: '/audiences'
      path: '/audiences'
      fullPath: '/audiences'
      preLoaderRoute: typeof AudiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$id': {
      id: '/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AccountsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AlertsRoute: AlertsRoute,
  AudiencesRoute: AudiencesRoute,
  CampaignsRoute: CampaignsRoute,
  CreativesRoute: CreativesRoute,
  LoginRoute: LoginRoute,
  OverviewRoute: OverviewRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SyncRoute: SyncRoute,
  UsersRoute: UsersRoute,
  AccountsIdRoute: AccountsIdRoute,
  ClientsIdRoute: ClientsIdRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
