/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as CreativesRouteImport } from './routes/creatives'
import { Route as ChatHistoryRouteImport } from './routes/chat-history'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AudiencesRouteImport } from './routes/audiences'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as InfrastructureIndexRouteImport } from './routes/infrastructure.index'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as AccountsIndexRouteImport } from './routes/accounts.index'
import { Route as ReportsTemplatesRouteImport } from './routes/reports.templates'
import { Route as ReportsNewRouteImport } from './routes/reports.new'
import { Route as ReportsRunIdRouteImport } from './routes/reports.$runId'
import { Route as PortalLoginRouteImport } from './routes/portal_.login'
import { Route as PortalReportsRouteImport } from './routes/portal.reports'
import { Route as PortalCreativesRouteImport } from './routes/portal.creatives'
import { Route as PortalCampaignsRouteImport } from './routes/portal.campaigns'
import { Route as InfrastructureProfilesRouteImport } from './routes/infrastructure.profiles'
import { Route as InfrastructurePixelsRouteImport } from './routes/infrastructure.pixels'
import { Route as InfrastructurePagesRouteImport } from './routes/infrastructure.pages'
import { Route as InfrastructureAdAccountsRouteImport } from './routes/infrastructure.ad-accounts'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'
import { Route as AccountsIdRouteImport } from './routes/accounts.$id'
import { Route as InfrastructureBusinessManagersIndexRouteImport } from './routes/infrastructure.business-managers.index'
import { Route as InfrastructureBusinessManagersIdRouteImport } from './routes/infrastructure.business-managers.$id'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativesRoute = CreativesRouteImport.update({
  id: '/creatives',
  path: '/creatives',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatHistoryRoute = ChatHistoryRouteImport.update({
  id: '/chat-history',
  path: '/chat-history',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiencesRoute = AudiencesRouteImport.update({
  id: '/audiences',
  path: '/audiences',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const InfrastructureIndexRoute = InfrastructureIndexRouteImport.update({
  id: '/infrastructure/',
  path: '/infrastructure/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsTemplatesRoute = ReportsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsNewRoute = ReportsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsRunIdRoute = ReportsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => ReportsRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal_/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalReportsRoute = PortalReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCreativesRoute = PortalCreativesRouteImport.update({
  id: '/creatives',
  path: '/creatives',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCampaignsRoute = PortalCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => PortalRoute,
} as any)
const InfrastructureProfilesRoute = InfrastructureProfilesRouteImport.update({
  id: '/infrastructure/profiles',
  path: '/infrastructure/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructurePixelsRoute = InfrastructurePixelsRouteImport.update({
  id: '/infrastructure/pixels',
  path: '/infrastructure/pixels',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructurePagesRoute = InfrastructurePagesRouteImport.update({
  id: '/infrastructure/pages',
  path: '/infrastructure/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureAdAccountsRoute =
  InfrastructureAdAccountsRouteImport.update({
    id: '/infrastructure/ad-accounts',
    path: '/infrastructure/ad-accounts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIdRoute = AccountsIdRouteImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureBusinessManagersIndexRoute =
  InfrastructureBusinessManagersIndexRouteImport.update({
    id: '/infrastructure/business-managers/',
    path: '/infrastructure/business-managers/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InfrastructureBusinessManagersIdRoute =
  InfrastructureBusinessManagersIdRouteImport.update({
    id: '/infrastructure/business-managers/$id',
    path: '/infrastructure/business-managers/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/alerts': typeof AlertsRoute
  '/audiences': typeof AudiencesRoute
  '/campaigns': typeof CampaignsRoute
  '/chat-history': typeof ChatHistoryRoute
  '/creatives': typeof CreativesRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/portal': typeof PortalRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sync': typeof SyncRoute
  '/users': typeof UsersRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/clients/$id': typeof ClientsIdRoute
  '/infrastructure/ad-accounts': typeof InfrastructureAdAccountsRoute
  '/infrastructure/pages': typeof InfrastructurePagesRoute
  '/infrastructure/pixels': typeof InfrastructurePixelsRoute
  '/infrastructure/profiles': typeof InfrastructureProfilesRoute
  '/portal/campaigns': typeof PortalCampaignsRoute
  '/portal/creatives': typeof PortalCreativesRoute
  '/portal/reports': typeof PortalReportsRoute
  '/portal/login': typeof PortalLoginRoute
  '/reports/$runId': typeof ReportsRunIdRoute
  '/reports/new': typeof ReportsNewRoute
  '/reports/templates': typeof ReportsTemplatesRoute
  '/accounts/': typeof AccountsIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/infrastructure/': typeof InfrastructureIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/infrastructure/business-managers/$id': typeof InfrastructureBusinessManagersIdRoute
  '/infrastructure/business-managers/': typeof InfrastructureBusinessManagersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/alerts': typeof AlertsRoute
  '/audiences': typeof AudiencesRoute
  '/campaigns': typeof CampaignsRoute
  '/chat-history': typeof ChatHistoryRoute
  '/creatives': typeof CreativesRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sync': typeof SyncRoute
  '/users': typeof UsersRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/clients/$id': typeof ClientsIdRoute
  '/infrastructure/ad-accounts': typeof InfrastructureAdAccountsRoute
  '/infrastructure/pages': typeof InfrastructurePagesRoute
  '/infrastructure/pixels': typeof InfrastructurePixelsRoute
  '/infrastructure/profiles': typeof InfrastructureProfilesRoute
  '/portal/campaigns': typeof PortalCampaignsRoute
  '/portal/creatives': typeof PortalCreativesRoute
  '/portal/reports': typeof PortalReportsRoute
  '/portal/login': typeof PortalLoginRoute
  '/reports/$runId': typeof ReportsRunIdRoute
  '/reports/new': typeof ReportsNewRoute
  '/reports/templates': typeof ReportsTemplatesRoute
  '/accounts': typeof AccountsIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/infrastructure': typeof InfrastructureIndexRoute
  '/portal': typeof PortalIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/infrastructure/business-managers/$id': typeof InfrastructureBusinessManagersIdRoute
  '/infrastructure/business-managers': typeof InfrastructureBusinessManagersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/alerts': typeof AlertsRoute
  '/audiences': typeof AudiencesRoute
  '/campaigns': typeof CampaignsRoute
  '/chat-history': typeof ChatHistoryRoute
  '/creatives': typeof CreativesRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/portal': typeof PortalRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sync': typeof SyncRoute
  '/users': typeof UsersRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/clients/$id': typeof ClientsIdRoute
  '/infrastructure/ad-accounts': typeof InfrastructureAdAccountsRoute
  '/infrastructure/pages': typeof InfrastructurePagesRoute
  '/infrastructure/pixels': typeof InfrastructurePixelsRoute
  '/infrastructure/profiles': typeof InfrastructureProfilesRoute
  '/portal/campaigns': typeof PortalCampaignsRoute
  '/portal/creatives': typeof PortalCreativesRoute
  '/portal/reports': typeof PortalReportsRoute
  '/portal_/login': typeof PortalLoginRoute
  '/reports/$runId': typeof ReportsRunIdRoute
  '/reports/new': typeof ReportsNewRoute
  '/reports/templates': typeof ReportsTemplatesRoute
  '/accounts/': typeof AccountsIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/infrastructure/': typeof InfrastructureIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/infrastructure/business-managers/$id': typeof InfrastructureBusinessManagersIdRoute
  '/infrastructure/business-managers/': typeof InfrastructureBusinessManagersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/alerts'
    | '/audiences'
    | '/campaigns'
    | '/chat-history'
    | '/creatives'
    | '/finance'
    | '/login'
    | '/overview'
    | '/portal'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/sync'
    | '/users'
    | '/accounts/$id'
    | '/clients/$id'
    | '/infrastructure/ad-accounts'
    | '/infrastructure/pages'
    | '/infrastructure/pixels'
    | '/infrastructure/profiles'
    | '/portal/campaigns'
    | '/portal/creatives'
    | '/portal/reports'
    | '/portal/login'
    | '/reports/$runId'
    | '/reports/new'
    | '/reports/templates'
    | '/accounts/'
    | '/clients/'
    | '/infrastructure/'
    | '/portal/'
    | '/reports/'
    | '/infrastructure/business-managers/$id'
    | '/infrastructure/business-managers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/alerts'
    | '/audiences'
    | '/campaigns'
    | '/chat-history'
    | '/creatives'
    | '/finance'
    | '/login'
    | '/overview'
    | '/settings'
    | '/signup'
    | '/sync'
    | '/users'
    | '/accounts/$id'
    | '/clients/$id'
    | '/infrastructure/ad-accounts'
    | '/infrastructure/pages'
    | '/infrastructure/pixels'
    | '/infrastructure/profiles'
    | '/portal/campaigns'
    | '/portal/creatives'
    | '/portal/reports'
    | '/portal/login'
    | '/reports/$runId'
    | '/reports/new'
    | '/reports/templates'
    | '/accounts'
    | '/clients'
    | '/infrastructure'
    | '/portal'
    | '/reports'
    | '/infrastructure/business-managers/$id'
    | '/infrastructure/business-managers'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/alerts'
    | '/audiences'
    | '/campaigns'
    | '/chat-history'
    | '/creatives'
    | '/finance'
    | '/login'
    | '/overview'
    | '/portal'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/sync'
    | '/users'
    | '/accounts/$id'
    | '/clients/$id'
    | '/infrastructure/ad-accounts'
    | '/infrastructure/pages'
    | '/infrastructure/pixels'
    | '/infrastructure/profiles'
    | '/portal/campaigns'
    | '/portal/creatives'
    | '/portal/reports'
    | '/portal_/login'
    | '/reports/$runId'
    | '/reports/new'
    | '/reports/templates'
    | '/accounts/'
    | '/clients/'
    | '/infrastructure/'
    | '/portal/'
    | '/reports/'
    | '/infrastructure/business-managers/$id'
    | '/infrastructure/business-managers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AlertsRoute: typeof AlertsRoute
  AudiencesRoute: typeof AudiencesRoute
  CampaignsRoute: typeof CampaignsRoute
  ChatHistoryRoute: typeof ChatHistoryRoute
  CreativesRoute: typeof CreativesRoute
  FinanceRoute: typeof FinanceRoute
  LoginRoute: typeof LoginRoute
  OverviewRoute: typeof OverviewRoute
  PortalRoute: typeof PortalRouteWithChildren
  ReportsRoute: typeof ReportsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SyncRoute: typeof SyncRoute
  UsersRoute: typeof UsersRoute
  AccountsIdRoute: typeof AccountsIdRoute
  ClientsIdRoute: typeof ClientsIdRoute
  InfrastructureAdAccountsRoute: typeof InfrastructureAdAccountsRoute
  InfrastructurePagesRoute: typeof InfrastructurePagesRoute
  InfrastructurePixelsRoute: typeof InfrastructurePixelsRoute
  InfrastructureProfilesRoute: typeof InfrastructureProfilesRoute
  PortalLoginRoute: typeof PortalLoginRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  InfrastructureIndexRoute: typeof InfrastructureIndexRoute
  InfrastructureBusinessManagersIdRoute: typeof InfrastructureBusinessManagersIdRoute
  InfrastructureBusinessManagersIndexRoute: typeof InfrastructureBusinessManagersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creatives': {
      id: '/creatives'
      path: '/creatives'
      fullPath: '/creatives'
      preLoaderRoute: typeof CreativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-history': {
      id: '/chat-history'
      path: '/chat-history'
      fullPath: '/chat-history'
      preLoaderRoute: typeof ChatHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiences': {
      id: '/audiences'
      path: '/audiences'
      fullPath: '/audiences'
      preLoaderRoute: typeof AudiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/infrastructure/': {
      id: '/infrastructure/'
      path: '/infrastructure'
      fullPath: '/infrastructure/'
      preLoaderRoute: typeof InfrastructureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/templates': {
      id: '/reports/templates'
      path: '/templates'
      fullPath: '/reports/templates'
      preLoaderRoute: typeof ReportsTemplatesRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/new': {
      id: '/reports/new'
      path: '/new'
      fullPath: '/reports/new'
      preLoaderRoute: typeof ReportsNewRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/$runId': {
      id: '/reports/$runId'
      path: '/$runId'
      fullPath: '/reports/$runId'
      preLoaderRoute: typeof ReportsRunIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/portal_/login': {
      id: '/portal_/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/reports': {
      id: '/portal/reports'
      path: '/reports'
      fullPath: '/portal/reports'
      preLoaderRoute: typeof PortalReportsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/creatives': {
      id: '/portal/creatives'
      path: '/creatives'
      fullPath: '/portal/creatives'
      preLoaderRoute: typeof PortalCreativesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/campaigns': {
      id: '/portal/campaigns'
      path: '/campaigns'
      fullPath: '/portal/campaigns'
      preLoaderRoute: typeof PortalCampaignsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/infrastructure/profiles': {
      id: '/infrastructure/profiles'
      path: '/infrastructure/profiles'
      fullPath: '/infrastructure/profiles'
      preLoaderRoute: typeof InfrastructureProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/pixels': {
      id: '/infrastructure/pixels'
      path: '/infrastructure/pixels'
      fullPath: '/infrastructure/pixels'
      preLoaderRoute: typeof InfrastructurePixelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/pages': {
      id: '/infrastructure/pages'
      path: '/infrastructure/pages'
      fullPath: '/infrastructure/pages'
      preLoaderRoute: typeof InfrastructurePagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/ad-accounts': {
      id: '/infrastructure/ad-accounts'
      path: '/infrastructure/ad-accounts'
      fullPath: '/infrastructure/ad-accounts'
      preLoaderRoute: typeof InfrastructureAdAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$id': {
      id: '/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AccountsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/business-managers/': {
      id: '/infrastructure/business-managers/'
      path: '/infrastructure/business-managers'
      fullPath: '/infrastructure/business-managers/'
      preLoaderRoute: typeof InfrastructureBusinessManagersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/business-managers/$id': {
      id: '/infrastructure/business-managers/$id'
      path: '/infrastructure/business-managers/$id'
      fullPath: '/infrastructure/business-managers/$id'
      preLoaderRoute: typeof InfrastructureBusinessManagersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortalRouteChildren {
  PortalCampaignsRoute: typeof PortalCampaignsRoute
  PortalCreativesRoute: typeof PortalCreativesRoute
  PortalReportsRoute: typeof PortalReportsRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalCampaignsRoute: PortalCampaignsRoute,
  PortalCreativesRoute: PortalCreativesRoute,
  PortalReportsRoute: PortalReportsRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface ReportsRouteChildren {
  ReportsRunIdRoute: typeof ReportsRunIdRoute
  ReportsNewRoute: typeof ReportsNewRoute
  ReportsTemplatesRoute: typeof ReportsTemplatesRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsRunIdRoute: ReportsRunIdRoute,
  ReportsNewRoute: ReportsNewRoute,
  ReportsTemplatesRoute: ReportsTemplatesRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AlertsRoute: AlertsRoute,
  AudiencesRoute: AudiencesRoute,
  CampaignsRoute: CampaignsRoute,
  ChatHistoryRoute: ChatHistoryRoute,
  CreativesRoute: CreativesRoute,
  FinanceRoute: FinanceRoute,
  LoginRoute: LoginRoute,
  OverviewRoute: OverviewRoute,
  PortalRoute: PortalRouteWithChildren,
  ReportsRoute: ReportsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SyncRoute: SyncRoute,
  UsersRoute: UsersRoute,
  AccountsIdRoute: AccountsIdRoute,
  ClientsIdRoute: ClientsIdRoute,
  InfrastructureAdAccountsRoute: InfrastructureAdAccountsRoute,
  InfrastructurePagesRoute: InfrastructurePagesRoute,
  InfrastructurePixelsRoute: InfrastructurePixelsRoute,
  InfrastructureProfilesRoute: InfrastructureProfilesRoute,
  PortalLoginRoute: PortalLoginRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  InfrastructureIndexRoute: InfrastructureIndexRoute,
  InfrastructureBusinessManagersIdRoute: InfrastructureBusinessManagersIdRoute,
  InfrastructureBusinessManagersIndexRoute:
    InfrastructureBusinessManagersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
